### ISSUE TITLE
Participantモデルへのカラム追加、Ticketモデルへの関連づけ

### ISSUE THREAD

**Issue by shogo0525** [shogo0525/huboo#16]
- [x] キャンセル日時：canceled_at, datetime
- [x] コメント：comment, string
- [x] チケットモデルへの関連づけカラムも追加する
- [x] 参加ボタンを押すときに、チケットIDも挿入するようにする

**Comment by shogo0525** [comment]
コメントはmessageのほうがいい？悩まし

**Comment by shogo0525** [comment]
あ、Ticketモデルへの関連づけも必要なのか。。。

**Comment by uenobu106** [comment]
コメントはcomment：string型よりtext型のがいいですかね？

**Comment by shogo0525** [comment]
コメントはあまり長いデータを受け付けたくないかなーと思いstringにしてました！
@ezawa800 どう思いますか？

**Comment by ezawa800** [comment]
コメントは短いほうが良いと思います。（スパム対策にも若干なる？）
もし、長いコメントが必要な場合は分けて投稿してもらえば大丈夫ですし。

**Comment by shogo0525** [comment]
@ezawa800 あ、コメントというのは、参加ボタンを押すときに、「よろしくお願いいたします！」というような内容を入れるためのもので、複数投稿はできない想定です。

**Comment by ezawa800** [comment]
@shogo0525 あ、そうか。プロジェクトに対するコメントと混同していました。
短いと困ることは無いと思うので、string型で良いと思います。

**Comment by shogo0525** [comment]
@ezawa800 プロジェクトというかイベントっすね（笑）
@uenobu106 ということで、string型でいいと思いますっ！text型が良いケースがあれば教えてください。

**Comment by shogo0525** [comment]
こちら僕が引き継ぎます。
