### ISSUE TITLE
SNSログインができるようにする

### ISSUE THREAD

**Issue by ezawa800** [shogo0525/huboo#21]
FacebookとTwitter（Instagram?）でログインできるようにする。
deviseで簡単にできそう？
http://ticklecode.com/fb_omniauth/

**Comment by shogo0525** [comment]
deviseでいけます！

**Comment by ezawa800** [comment]
SNSログインのためには、Herokuへのデプロイなどが必要なため、AppをWeb上に公開してから着手することにしました。
一旦クローズします。
